version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
  app_spring_rabbit_mq:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'app_spring_rabbit_mq_container'
    ports:
      - 8080:8080
    networks:
      - rabbitmq_go_net
networks:
  rabbitmq_go_net:
    driver: bridge